import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class BlobTester {
	public static void main (String [] args) throws NoSuchAlgorithmException, IOException{
//		System.out.print("HashCode Generated by SHA-1 for: ");
//		String input = "hello world";
//		Blob blobithy = new Blob(input);
//		String sha = blobithy.getSha();
//		System.out.print("\n" + input + ": " + sha);
		
//		Blob blobiford = new Blob("among.txt");
		Index jones = new Index();
		jones.add("naruto");
		jones.add("luffy");
		jones.add("goku");
		jones.remove("naruto");
		
//        String s1 = "GeeksForGeeks";
//        System.out.println("\n" + s1 + " : " + BlobCreationTechnique(s1));
// 
//        String s2 = "hello world";
//        System.out.println("\n" + s2 + " : " + BlobCreationTechnique(s2));
	}
}
